### ISSUE TITLE
Review Me [NuhcanATAR]

### ISSUE THREAD

**Issue by NuhcanATAR** [VB10/review-me#12]
Repo URL: https://github.com/NuhcanATAR/caffely
Diğer:

**Comment by VB10** [comment]
Merhaba sonradan template kısmına iş arıyorum ve freelance yapıyorum yapmıyorum olarak iki alan ekledim buna göre issue güncellersen paylaşım yaparken elimden geldiğince bu şekilde öne çıkarmaya çalışacağım. şimdiden eline sağlık <3

---
İş arıyorum: Evet/Hayır
Freelance proje alıyorum: Evet/Hayır
Repo URL:
Diğer:

**Comment by VB10** [comment]
@NuhcanATAR eline sağlık bu reponun çok eksiği var readme vs çok iyi ama geliştirip ilerliyen zamanda bekliyorum balta geliyor sana
