### ISSUE TITLE
Review Me [HikmetMelikk]

### ISSUE THREAD

**Issue by HikmetMelikk** [VB10/review-me#15]
Repo URL: https://github.com/HikmetMelikk/take-a-bite
Diğer: Genel olarak projelerim temel seviyede, teknik çalışmalara yönelik oldu. Repo URL kısmına eklediğim proje son zamanda paylaştığınız Food App projeleri için düşünülmüş food app'ler için farklı konseptte düşündüğüm bir proje. Tamamen bitirilmedi araya birkaç farklı iş girdi, bununla birlikte temel düşünceyi aşıladığımı düşünüyorum. https://hikmetmelik.tech React.js ile yazdığım sitemi de incelerseniz sevinirim. Şimdiden teşekkür ederim.

**Comment by VB10** [comment]
@HikmetMelikk repoyu kapattığın için siliyorum eline sağlıkk
