### ISSUE TITLE
Review Me [hsefakcay]

### ISSUE THREAD

**Issue by hsefakcay** [VB10/review-me#16]
İş arıyorum: **Evet**
Freelance proje alıyorum: **Evet**
Repo URL :https://github.com/hsefakcay/eat_now_app
Diğer:
Projemi linkedln de paylaşmıştım hocam. İnceleyip eksiklerimi projenin issues kısmına eklemiştiniz. Eksiklerimi gidermeye çalıştım. Tekrar incelerseniz sevinirim. Şimdiden teşekkürler.

**Comment by VB10** [comment]
@hsefakcay senin repona bırakıtğım issuler hala açık duruyor önce onları yorum yapıp bunları ekledim bunları yaptım diye paylaşman gerekir ondan es geçiyorum seni bir sonrakine
