### ISSUE TITLE
Review Me [ErenBal1]

### ISSUE THREAD

**Issue by ErenBal1** [VB10/review-me#17]
Repo URL: https://github.com/ErenBal1/gapsec-stories
Diğer: Arkadaşımla geliştirdiğimiz bir oyundu hocam. Hatalarımızı görmek isteriz

**Comment by VB10** [comment]
Merhaba sonradan template kısmına iş arıyorum ve freelance yapıyorum yapmıyorum olarak iki alan ekledim buna göre issue güncellersen paylaşım yaparken elimden geldiğince bu şekilde öne çıkarmaya çalışacağım. şimdiden eline sağlık <3

---
İş arıyorum: Evet/Hayır
Freelance proje alıyorum: Evet/Hayır
Repo URL:
Diğer:
