### ISSUE TITLE
Review Me [abdullah017]

### ISSUE THREAD

**Issue by abdullah017** [VB10/review-me#18]
**İş arıyorum:  **Evet**
Freelance proje alıyorum: **Evet****

Repo URL: https://github.com/abdullah017/flutter_abdullahtasdev_blog

Diğer: Bu proje Flutter Web - Mobil Blog App konuludur. 

Proje Hasura- GraphQL ve Firebase Auth - Storage ile desteklenmiştir.

**Comment by VB10** [comment]
Merhaba sonradan template kısmına iş arıyorum ve freelance yapıyorum yapmıyorum olarak iki alan ekledim buna göre issue güncellersen paylaşım yaparken elimden geldiğince bu şekilde öne çıkarmaya çalışacağım. şimdiden eline sağlık <3

---
İş arıyorum: Evet/Hayır
Freelance proje alıyorum: Evet/Hayır
Repo URL:
Diğer:

**Comment by VB10** [comment]
eline sağlık @abdullah017 eksiklerini yazdım geliştirmen gereken noktalar var
