### ISSUE TITLE
Review Me [kuru0777]

### ISSUE THREAD

**Issue by kuru0777** [VB10/review-me#19]
İş arıyorum: Evet
Freelance proje alıyorum: Hayır
Repo URL:https://github.com/kuru0777/face-recognition-with-flutter 

Diğer:Bitirme projesi yüz tanıma uygulaması yapmıştım Google ml kit ve facenet modeli kullanılarak geliştrildi.

**Comment by VB10** [comment]
Merhaba sonradan template kısmına iş arıyorum ve freelance yapıyorum yapmıyorum olarak iki alan ekledim buna göre issue güncellersen paylaşım yaparken elimden geldiğince bu şekilde öne çıkarmaya çalışacağım. şimdiden eline sağlık <3

---
İş arıyorum: Evet/Hayır
Freelance proje alıyorum: Evet/Hayır
Repo URL:
Diğer:

**Comment by VB10** [comment]
kendini geliştirmeye devam etmelisin eksiğin çok.
