### ISSUE TITLE
Review Me [HasancanCakicioglu]

### ISSUE THREAD

**Issue by HasancanCakicioglu** [VB10/review-me#20]
Repo URL : https://github.com/HasancanCakicioglu/Solution_Challenge_2023_FikirAtlasi
Diğer : firebase functionlar ile vector db pinecone bağlantısı kuruldu semantic search için.

**Comment by HasancanCakicioglu** [comment]
İş arıyorum: Hayır
Freelance proje alıyorum: Hayır
Staj arıyorum : EVET

**Comment by VB10** [comment]
genel olarak projen büyük kapsamlı bir kaç noktaya değindim ama sevdim projeni eline sağlık 🎉 kalp geliyor benden
