### ISSUE TITLE
Review Me [Harunn33]

### ISSUE THREAD

**Issue by Harunn33** [VB10/review-me#21]
İş arıyorum: Evet
Freelance proje alıyorum: Hayır
Repo URL:https://github.com/Harunn33/Theme-Play
Diğer: in development

**Comment by VB10** [comment]
Merhaba sonradan template kısmına iş arıyorum ve freelance yapıyorum yapmıyorum olarak iki alan ekledim buna göre issue güncellersen paylaşım yaparken elimden geldiğince bu şekilde öne çıkarmaya çalışacağım. şimdiden eline sağlık <3

---
İş arıyorum: Evet/Hayır
Freelance proje alıyorum: Evet/Hayır
Repo URL:
Diğer:

**Comment by VB10** [comment]
@Harunn33 eline sağlık repoda readme olsa güzel olurdu ondan kalbim kırık ama genel olarak yaklaşım ve eklemleri sevdim
