### ISSUE TITLE
Review Me [tahsin-emre]

### ISSUE THREAD

**Issue by tahsin-emre** [VB10/review-me#3]
Proje henüz tamamlanmadı. Genel bir feedback ile release çıkmadan gerekli düzenlemeleri yapmak isterim.
ek. Modellere JSON Serializable eklenecek.

Repo URL: https://github.com/tahsin-emre/voxpollui/tree/main
Diğer:

**Comment by VB10** [comment]
@tahsin-emre ne yazık ki repona issue açamıyorumm (: başka zamana

**Comment by tahsin-emre** [comment]
> @tahsin-emre ne yazık ki repona issue açamıyorumm (: başka zamana

Sorun yok haberleşmek üzere :)
