### ISSUE TITLE
Review Me [ertekinbatuhan]

### ISSUE THREAD

**Issue by ertekinbatuhan** [VB10/review-me#6]
Repo URL: https://github.com/ertekinbatuhan/BudgetBuddy
Diğer: Öncelikle, review’iniz benim için gerçekten çok değerli ve bu fırsatı sunduğunuz için teşekkür ederim. Geri bildirimleriniz sayesinde projemi  daha iyi hale getirme şansı bulacağıma inanıyorum.

**Comment by VB10** [comment]
@ertekinbatuhan eline emeğine sağlık severek like attım
