### ISSUE TITLE
Review Me [ozcanbayram]

### ISSUE THREAD

**Issue by ozcanbayram** [VB10/review-me#7]
Repo URL:  https://github.com/ozcanbayram/Flutter-Dart-Helper
Diğer: Bu repomda sizin eğitimlerinizden ve bir çok kaynaktan kendi yorumlarımla bilgiler ekliyorum (Henüz devam ediyorum.). 
Hazır widgetlar tasarlıyorum, sizin ve diğer arkadaşların da kendi widgetlarını, bilgilerini burada paylaşarak güzel bir kaynak oluşturmayı istiyorum.  
(Bu repon, desteklerin ve emeklerin için çok teşekkür ederim Veli abi tüm arkadaşlarla bu repo sayesinde birbirimize destek vererek birlikte çok daha ileri gidebiliriz.)

**Comment by VB10** [comment]
@ozcanbayram projene baktım çok iyi duruyor genel bir code review yapmak mümkün değil ama fikri yaptıklarnı sevdim kalp bırakıyorumm

**Comment by ozcanbayram** [comment]
Teşekkür ederim :)
